<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="repository" nsURI="urn:repository" nsPrefix="repository">
  <eClassifiers xsi:type="ecore:EClass" name="ContextType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childContextTypeLinks"
        upperBound="-1" eType="#//ChildContextTypeLink" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childDocumentTypeLinks"
        upperBound="-1" eType="#//ChildDocumentTypeLink" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootDocumentType" eType="#//DocumentType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedClass" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The generated class is only relevant if the context type has no root document type. It this case, it specifies the class that will be used to represent contexts of this type."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChildContextTypeLink">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextType" lowerBound="1"
        eType="#//ContextType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChildDocumentTypeLink">
    <eStructuralFeatures xsi:type="ecore:EReference" name="documentType" lowerBound="1"
        eType="#//DocumentType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DocumentType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filePattern" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootRefObjectTypes" upperBound="-1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Context">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//ContextType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootDocument" eType="#//Document"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childDocuments" upperBound="-1"
        eType="#//ChildDocument" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childContexts" upperBound="-1"
        eType="#//ChildContext" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChildDocument">
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" lowerBound="1" eType="#//ChildDocumentTypeLink"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="document" lowerBound="1"
        eType="#//Document" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChildContext">
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" lowerBound="1" eType="#//ChildContextTypeLink"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
        eType="#//Context" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Document">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//DocumentType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RepositoryMetadata">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextTypes" upperBound="-1"
        eType="#//ContextType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="documentTypes" upperBound="-1"
        eType="#//DocumentType" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
